<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.isii</groupId>
    <artifactId>ProyectoCampingParty</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <repositories>
        <repository>
            <id>unknown-jars-temp-repo</id>
            <name>A temporary repository created by NetBeans for libraries and jars it could not identify. Please replace the dependencies in this repository with correct ones and delete this repository.</name>
            <url>file:${project.basedir}/lib</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>com.toedter</groupId>
            <artifactId>jcalendar</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>3.6.2</version>
        </dependency>
        <dependency>
            <groupId>unknown.binary</groupId>
            <artifactId>jgoodies-common-1.2.0</artifactId>
            <version>SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.github.lgooddatepicker</groupId>
            <artifactId>LGoodDatePicker</artifactId>
            <version>11.2.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.dj-raven</groupId>
            <artifactId>swing-datetime-picker</artifactId>
            <version>2.1.3</version>
        </dependency>
    </dependencies>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
        <exec.mainClass>com.campingparty.main.ProyectoCampingParty</exec.mainClass>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <includes>
                        <include>com/campingparty/main/**/*.java</include>
                        <include>com/campingparty/themes/**/*.java</include>
                        <include>com/campingparty/modelo/**/*.java</include>
                        <include>com/campingparty/controlador/ControladorPrincipal.java</include>
                        <include>com/campingparty/vista/IVista.java</include>
                        <include>com/campingparty/vista/Welcome.java</include>
                        <include>com/campingparty/vista/VistaBienvenida.java</include>
                        <include>com/campingparty/vista/VistaClienteLogin.java</include>
                        <include>com/campingparty/vista/VistaStaffLogin.java</include>
                        <include>com/campingparty/vista/VistaCliente.java</include>
                        <include>com/campingparty/vista/StaffMain.java</include>
                        <include>com/campingparty/vista/VistaClienteModificarReserva.java</include>
                        <include>com/campingparty/vista/VistaReservas.java</include>
                        <include>com/campingparty/vista/ActividadSeleccionada.java</include>
                    </includes>
                    <excludes>
                        <exclude>VISTA/**</exclude>
                        <exclude>MODELO/**</exclude>
                        <exclude>CONTROLADOR/**</exclude>
                        <exclude>MAIN/**</exclude>
                        <exclude>com/campingparty/modelo/Parcelas.java</exclude>
                        <exclude>com/campingparty/modelo/Reservas.java</exclude>
                        <exclude>com/campingparty/modelo/Participacion.java</exclude>
                        <exclude>com/campingparty/modelo/Valid.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>